codecov:
  notify:
    require_ci_to_pass: no
comment:
  layout: header, changes, diff, sunburst, files
coverage:
  status:
    patch:
      default:
        target: 50%
        only_pulls: true
    # project will give us the diff in the total code coverage between a commit
    # and its parent
    project:
      default:
        target: auto
        threshold: "15%"
    changes: false
ignore:
  - "vendor/*"
