#!/usr/bin/env bash
# Entrypoint for jenkins janky CI build
set -eu -o pipefail

# Rebase to master so codecov will provide valid diff report
git config --global user.email "ci@moby"
git config --global user.name "CI"
git fetch origin master
git rebase --merge origin/master

hack/validate/default
hack/test/unit
bash <(curl -s https://codecov.io/bash) \
    -f coverage.txt \
    -C "$GIT_SHA1" -Z

hack/make.sh \
	binary-daemon \
	dynbinary \
	test-docker-py \
	test-integration-flaky \
	test-integration \
	cross
