
// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time information.
const (
	GitCommit             string = "703b834df3"
	Version               string = "0.0.0-dev"
	BuildTime             string = "03/17/2022 21:36:41"
	PlatformName          string = ""
	ProductName           string = ""
	DefaultProductLicense string = ""
)

// AUTOGENERATED FILE; see hack\make\.go-autogen.ps1
